server:
  port: 8080
  servlet:
    context-path: /thea-sso-server

spring:
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########

thea:
  sso:
    redis:
      address: redis://127.0.0.1:6379
      expire:
        minute: 1440